//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 05:27:39 PM CEST 
//


package org.w3._2003._01.geo.wgs84_pos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2003._01.geo.wgs84_pos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Lat_QNAME = new QName("http://www.w3.org/2003/01/geo/wgs84_pos#", "lat");
    private final static QName _Long_QNAME = new QName("http://www.w3.org/2003/01/geo/wgs84_pos#", "long");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2003._01.geo.wgs84_pos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#", name = "lat")
    public JAXBElement<String> createLat(String value) {
        return new JAXBElement<String>(_Lat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#", name = "long")
    public JAXBElement<String> createLong(String value) {
        return new JAXBElement<String>(_Long_QNAME, String.class, null, value);
    }

}
