//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.24 at 10:56:00 AM CEST 
//


package generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}links"/>
 *         &lt;element ref="{}published"/>
 *         &lt;element ref="{}summary"/>
 *         &lt;element ref="{}content"/>
 *         &lt;element ref="{}placeformed"/>
 *         &lt;element ref="{}formationlist"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "links",
    "published",
    "summary",
    "content",
    "placeformed",
    "formationlist"
})
@XmlRootElement(name = "bio")
public class Bio {

    @XmlElement(required = true)
    protected Links links;
    @XmlElement(required = true)
    protected String published;
    @XmlElement(required = true)
    protected String summary;
    @XmlElement(required = true)
    protected String content;
    @XmlElement(required = true)
    protected String placeformed;
    @XmlElement(required = true)
    protected Formationlist formationlist;

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link Links }
     *     
     */
    public Links getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link Links }
     *     
     */
    public void setLinks(Links value) {
        this.links = value;
    }

    /**
     * Gets the value of the published property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublished() {
        return published;
    }

    /**
     * Sets the value of the published property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublished(String value) {
        this.published = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the placeformed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceformed() {
        return placeformed;
    }

    /**
     * Sets the value of the placeformed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceformed(String value) {
        this.placeformed = value;
    }

    /**
     * Gets the value of the formationlist property.
     * 
     * @return
     *     possible object is
     *     {@link Formationlist }
     *     
     */
    public Formationlist getFormationlist() {
        return formationlist;
    }

    /**
     * Sets the value of the formationlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formationlist }
     *     
     */
    public void setFormationlist(Formationlist value) {
        this.formationlist = value;
    }

}
