//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.24 at 10:56:00 AM CEST 
//


package generated;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Content_QNAME = new QName("", "content");
    private final static QName _Summary_QNAME = new QName("", "summary");
    private final static QName _Ontour_QNAME = new QName("", "ontour");
    private final static QName _Listeners_QNAME = new QName("", "listeners");
    private final static QName _Mbid_QNAME = new QName("", "mbid");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Streamable_QNAME = new QName("", "streamable");
    private final static QName _Placeformed_QNAME = new QName("", "placeformed");
    private final static QName _Playcount_QNAME = new QName("", "playcount");
    private final static QName _Published_QNAME = new QName("", "published");
    private final static QName _Url_QNAME = new QName("", "url");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tags }
     * 
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link Stats }
     * 
     */
    public Stats createStats() {
        return new Stats();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link Lfm }
     * 
     */
    public Lfm createLfm() {
        return new Lfm();
    }

    /**
     * Create an instance of {@link Artist }
     * 
     */
    public Artist createArtist() {
        return new Artist();
    }

    /**
     * Create an instance of {@link Bio }
     * 
     */
    public Bio createBio() {
        return new Bio();
    }

    /**
     * Create an instance of {@link Formationlist }
     * 
     */
    public Formationlist createFormationlist() {
        return new Formationlist();
    }

    /**
     * Create an instance of {@link Formation }
     * 
     */
    public Formation createFormation() {
        return new Formation();
    }

    /**
     * Create an instance of {@link Yearfrom }
     * 
     */
    public Yearfrom createYearfrom() {
        return new Yearfrom();
    }

    /**
     * Create an instance of {@link Yearto }
     * 
     */
    public Yearto createYearto() {
        return new Yearto();
    }

    /**
     * Create an instance of {@link Similar }
     * 
     */
    public Similar createSimilar() {
        return new Similar();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content")
    public JAXBElement<String> createContent(String value) {
        return new JAXBElement<String>(_Content_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "summary")
    public JAXBElement<String> createSummary(String value) {
        return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ontour")
    public JAXBElement<BigInteger> createOntour(BigInteger value) {
        return new JAXBElement<BigInteger>(_Ontour_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "listeners")
    public JAXBElement<BigInteger> createListeners(BigInteger value) {
        return new JAXBElement<BigInteger>(_Listeners_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mbid")
    public JAXBElement<String> createMbid(String value) {
        return new JAXBElement<String>(_Mbid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "streamable")
    public JAXBElement<BigInteger> createStreamable(BigInteger value) {
        return new JAXBElement<BigInteger>(_Streamable_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "placeformed")
    public JAXBElement<String> createPlaceformed(String value) {
        return new JAXBElement<String>(_Placeformed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "playcount")
    public JAXBElement<BigInteger> createPlaycount(BigInteger value) {
        return new JAXBElement<BigInteger>(_Playcount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "published")
    public JAXBElement<String> createPublished(String value) {
        return new JAXBElement<String>(_Published_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "url")
    public JAXBElement<String> createUrl(String value) {
        return new JAXBElement<String>(_Url_QNAME, String.class, null, value);
    }

}
